---
version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make backend
    volumes:
      - ~/.bash_history:/root/.bash_history
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - frontend

  frontend:
    build: .
    command: make frontend
    ports:
      - "8888:8888"
    volumes:
      - .:/app
