---
functional:
  - Возможность просмотра на русском или английском языке
  - Возможность авторизации через Github
  - Возможность авторизации по email и паролю
  - Нельзя повторно зарегистрироваться по одному email
  - Возможность публикации резюме
  - Список резюме должен содержать дату публикации каждого и ссылку на профиль автора
  - Список резюме должен отображать количество просмотров и ответов на каждое
  - Список резюме должен быть доступен без регистрации
  - Возможность оставить рекомендацию от авторизованного пользователя
  - Возможность дать только одну рекомендацию по конкретному резюме
  - Доступность просмотра рекомендации без авторизации
  - Возможность поиска резюме по значениям направление, фамилия, имя, почта
  - Возможность фильтрации резюме по популярности, новизне, наличию рекомендаций
  - Возможность размещения вакансии
  - Список вакансий должен содержать дату публикации каждой
  - Возможность поиска вакансии по значениям направление, уровень, город
  - Ведение рейтинга пользователей по количеству лайков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - На сайте указано название организации, ОГРН, ИНН, адрес, телефон
  - Должна быть указана политика конфиденциальности
